
x<-c(20,65,15,50)
labels<-c("India","America","Srilanka","Nepal")
png(file="title_color.png")
pie(x,labels,main="Country Pie chart",col=rainbow(length(x)))
dev.off()

x<-c(20,65,15,50)
labels<-c("India","America","Srilanka","Nepal")
pie_percent<-round(100*x/sum(x),1)
png(file="per_pie.jpg")
pie(x,labels="Pie Chart",main="Country Pie chart",col=rainbow(length(x)))
legend("topright",c("India","America","Srilanka","Nepal"),cex=0.8)
fill=rainbow(length(x))
dev.off()

library(plotrix)
x<-c(20,65,15,50,45)
labels<-c("India","America","Srilanka","Nepal","Bhutan")
png(file="3d_f1.jpg")
pie3D(x,labels,explode=0.1,main="Country Pie Chart")
dev.off()